### ISSUE TITLE
Update glint

### ISSUE THREAD

**Issue by JohnBjrk** [tynanbe/rad#2]
I was testing `rad` with showtime. Unfortunately showtime depends on a newer version of `glint` so I had to update and patch `rad` a bit to make it work.

Would you consider to update to the newest `glint`?

I could prepare the work that I did into a PR, but I felt that it was hard to do the changes in a good way for the project since I'm not that familiar with the `rad` codebase.

**Comment by tynanbe** [comment]
Thanks for posting, and for your `rad` interest~

This issue is resolved by https://github.com/tynanbe/rad/commit/0527691e608fbfbeb5bb1b09f10800854ede1e72
